[features]
seeds = false
skip-lint = false

[programs.devnet]
credit_core = "FzUuFPcugpMGKprLLxZQbJwZFxPpdRrzSn1Q23usphCP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/zishan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"